### PR TITLE
DEV-835

### PR DESCRIPTION
**Pull request by tranlyvu**
updating joinProject method in class AdaterDeterLab.java  (SIO) to match changes in join_project_existing_user method (adapter-deterlab) to improve error handling

### CODE REVIEW

**Comment by tranlyvu** [comment]
if you plan to change name of the exception method, i think better do another branch, i was planning to make this branch to fix error handling for existing user to join project

**Comment by ZHANGChunwang** [comment]
Using your branch, I try to give a coding sample for the AdapterDeterLab class. Please follow the same standard / style when you improve other methods.

**Comment by tranlyvu** [comment]
local test not done yet

**Comment by ZHANGChunwang** [comment]
Good enough to merge, but need to run through the local tests...

**Pull request merged**
