### PR TITLE
DEV-581 Status check when users login

### PR DESCRIPTION
**Pull request by ZHANGChunwang**
This change is [Reviewable](https://reviewable.io/reviews/nus-ncl/services-in-one/124)

### CODE REVIEW

**Comment by ChrisZhong** [comment]
SonarQube analysis reported 1 issue

Note: The following issues were found on lines that were not modified in the pull request. Because these issues can't be reported as line comments, they are summarized here:

1. CRITICAL [AuthenticationServiceImpl.java#L63](https://github.com/nus-ncl/services-in-one/blob/655f2a868094323472ed0dc4870a05a4cea61a5b/service-authentication/src/main/java/sg/ncl/service/authentication/logic/AuthenticationServiceImpl.java#L63): The Cyclomatic Complexity of this method "login" is 12 which is greater than 10 authorized. [rule](https://sonarqube.com/coding_rules#rule_key=squid%3AMethodCyclomaticComplexity)

**Comment by ChrisZhong** [comment]
:-1: I cannot approve this because the code for the user status checks should be in the user service not the authentication service

**Comment by ZHANGChunwang** [comment]
Ok, fair enough. Then what is your suggestion for the implementation? In
the /login of web-service, we first connect to user service to check the
user status, if it is ok, then connect to authentication service for login?

Best Regards,
Chunwang

On Wed, Aug 31, 2016 at 6:30 PM, Christopher Zhong <notifications@github.com

**Comment by ChrisZhong** [comment]
:+1:

**Comment by ChrisZhong** [comment]
:+1:

**Pull request merged**
